 # The docker-compose.yml is the file that defines the setup of the docker-compose pipeline
version: '3' # version of docker-compose

# Each container is one service
services: # Now we are listing the containers that will be part of this pipeline

  # 1. Container
  tweet_collector:
    container_name: tweet_collector # the name of the actual docker container
    build: tweet_collector/ # Creates the image from the Dockerfile in the directory ./tweet_collector
    volumes: # links the local directory ./tweet_collector with the container directory /app and synchronizes them
    - ./tweet_collector/:/app
    depends_on:
      # depends_on in this case specifies that the tweet_collector container gets started only
      # after the mongodb container has been started
      # In order to connect to the mongodb database it has to be set up before we try to connect to it
      # Unfortunately depends_on just defines an order in which container are started, not in which they are
      # ready to operate
     - mongodb
  
  # 2. Container
  mongodb:
    container_name: mongodb
    image: mongo # Uses a predefined image, namely mongo
    ports:
    - 27017:27017
  
  # 3. Container: ETL-Job
  etl:
    container_name: etl
    build: etl
    volumes: 
    - ./etl/:/app
    depends_on:
    - postgres
    - mongodb
    
  # 4. Container: postgres
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    image: postgres
    ports: 
    - 5555:5432
    depends_on:
    - mongodb

  # 5. Container: slackbot

